### ISSUE TITLE
Add installation instructions

### ISSUE THREAD

**Issue by fredcallaway** [mhtess/webppl-csv#2]
I couldn't find it with npm, so I used
`npm install --prefix ~/.webppl https://github.com/mhtess/webppl-csv`

**Comment by mhtess** [comment]
Hi Fred, I've added install instructions and make some improvements to the code base. Let me know if there are any follow-up issues.

**Comment by fredcallaway** [comment]
Sweet! The distribution writing functionality is exactly what I need for a current project. I'm glad I procrastinated on implementing that 😄
